---
- name: prepare add apt repository
  tags: java
  apt:
    state=latest
    pkg=python-pycurl
    update_cache=yes

- name: add oracle apt repository
  tags: java
  apt_repository:
    repo=ppa:webupd8team/java

- name: confirm oracle licence
  tags: java
  shell: echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

- name: install oracle java 7
  tags: java
  apt:
    state=latest
    pkg=oracle-java7-installer
    update_cache=yes